import xo from 'eslint-config-xo';
import xoReact from 'eslint-config-xo-react';
import prettierConflicts from 'eslint-config-prettier';

const xoReactConfigs = xoReact().map(config => ({
  ...config,
  files: ['**/*.{jsx,tsx}'],
}));

const disabledRules = [
  '@stylistic/curly-newline',
  '@stylistic/padding-line-between-statements',
  '@typescript-eslint/array-type',
  '@typescript-eslint/await-thenable',
  '@typescript-eslint/consistent-generic-constructors',
  '@typescript-eslint/consistent-indexed-object-style',
  '@typescript-eslint/consistent-type-assertions',
  '@typescript-eslint/member-ordering',
  '@typescript-eslint/naming-convention',
  '@typescript-eslint/no-base-to-string',
  '@typescript-eslint/no-confusing-void-expression',
  '@typescript-eslint/no-deprecated',
  '@typescript-eslint/no-dynamic-delete',
  '@typescript-eslint/no-empty-function',
  '@typescript-eslint/no-floating-promises',
  '@typescript-eslint/no-inferrable-types',
  '@typescript-eslint/no-restricted-types',
  '@typescript-eslint/no-shadow',
  '@typescript-eslint/no-unnecessary-type-assertion',
  '@typescript-eslint/no-unsafe-argument',
  '@typescript-eslint/no-unsafe-assignment',
  '@typescript-eslint/no-unsafe-member-access',
  '@typescript-eslint/no-unsafe-type-assertion',
  '@typescript-eslint/no-unused-private-class-members',
  '@typescript-eslint/no-useless-default-assignment',
  '@typescript-eslint/non-nullable-type-assertion-style',
  '@typescript-eslint/prefer-includes',
  '@typescript-eslint/prefer-nullish-coalescing',
  '@typescript-eslint/prefer-optional-chain',
  '@typescript-eslint/prefer-promise-reject-errors',
  '@typescript-eslint/prefer-readonly',
  '@typescript-eslint/prefer-regexp-exec',
  '@typescript-eslint/promise-function-async',
  '@typescript-eslint/restrict-template-expressions',
  '@typescript-eslint/strict-void-return',
  '@typescript-eslint/switch-exhaustiveness-check',
  '@typescript-eslint/use-unknown-in-catch-callback-variable',
  'arrow-body-style',
  'capitalized-comments',
  'complexity',
  'eqeqeq',
  'func-names',
  'import-x/no-anonymous-default-export',
  'import-x/no-duplicates',
  'import-x/no-extraneous-dependencies',
  'import-x/no-unassigned-import',
  'import-x/order',
  'json/no-empty-keys',
  'logical-assignment-operators',
  'max-lines',
  'n/no-extraneous-import',
  'n/prefer-global/url',
  'new-cap',
  'no-await-in-loop',
  'no-else-return',
  'no-eq-null',
  'no-negated-condition',
  'no-restricted-globals',
  'no-warning-comments',
  'object-shorthand',
  'prefer-destructuring',
  'radix',
  'react-hooks/set-state-in-effect',
  'react/boolean-prop-naming',
  'react/forward-ref-uses-ref',
  'react/hook-use-state',
  'react/jsx-no-bind',
  'react/jsx-no-leaked-render',
  'react/jsx-no-target-blank',
  'react/jsx-sort-props',
  'react/no-unescaped-entities',
  'react/prefer-read-only-props',
  'react/self-closing-comp',
  'require-unicode-regexp',
  'unicorn/catch-error-name',
  'unicorn/explicit-length-check',
  'unicorn/filename-case',
  'unicorn/no-anonymous-default-export',
  'unicorn/no-array-callback-reference',
  'unicorn/no-array-for-each',
  'unicorn/no-array-reduce',
  'unicorn/no-array-reverse',
  'unicorn/no-array-sort',
  'unicorn/no-await-expression-member',
  'unicorn/no-hex-escape',
  'unicorn/no-immediate-mutation',
  'unicorn/no-lonely-if',
  'unicorn/no-negated-condition',
  'unicorn/no-unreadable-array-destructuring',
  'unicorn/no-useless-promise-resolve-reject',
  'unicorn/prefer-add-event-listener',
  'unicorn/prefer-at',
  'unicorn/prefer-blob-reading-methods',
  'unicorn/prefer-dom-node-append',
  'unicorn/prefer-global-this',
  'unicorn/prefer-query-selector',
  'unicorn/prefer-spread',
  'unicorn/prefer-string-raw',
  'unicorn/prefer-string-replace-all',
  'unicorn/prevent-abbreviations',
  'unicorn/switch-case-braces',
];

export default [
  ...xo({
    browser: true,
  }),
  ...xoReactConfigs,
  {
    rules: {
      ...Object.fromEntries(disabledRules.map(rule => [rule, 'off'])),
      'no-alert': 'off',
      'no-console': 'off',
    },
  },
  prettierConflicts,
];
