export type OSIKeyword =
  | 'osi-approved'
  | 'discouraged'
  | 'non-reusable'
  | 'redundant'
  | 'popular'
  | 'obsolete'
  | 'copyleft'
  | 'special-purpose'
  | 'permissive'
  | 'miscellaneous'
  | 'retired';

export type License = {
  // From SPDX list
  id: string;
  name: string;
  isOsiApproved?: true;
  isDeprecatedLicenseId?: true;

  // From OSI list
  keywords?: OSIKeyword[];
};

export type Licenses = Record<string, License>;

// Keep licenses in a secondary bundle but load it eagerly
export const licensesPromise: Promise<Licenses> = import(
  './licenses_autogenerated.json'
).then(m => ((m as { default?: Licenses }).default ?? m) as Licenses);
