#!/usr/bin/env node

// This script fetches the OSI and SPDX license lists and combines the two in a
// single file that provides the most-interesting (to us) information from both.

import fs from 'node:fs/promises';

const LICENSE_FILE = new URL(
  '../lib/licenses_autogenerated.json',
  import.meta.url,
);

const OSI_URL = 'https://api.opensource.org/licenses/';
const SPDX_URL =
  'https://raw.githubusercontent.com/spdx/license-list-data/main/json/licenses.json';

const spdx = await (await fetch(SPDX_URL)).json();
const osi = await (await fetch(OSI_URL)).json();

const licenses = new Map();

function getLicense(id) {
  const lowerId = id.toLowerCase();
  if (!licenses.has(lowerId)) {
    licenses.set(lowerId, {});
  }
  return licenses.get(lowerId);
}

for (const {
  licenseId,
  name,
  isOsiApproved,
  isDeprecatedLicenseId,
} of spdx.licenses) {
  const l = getLicense(licenseId);
  l.id = licenseId;
  l.name = name;

  if (isOsiApproved) l.isOsiApproved = true;
  if (isDeprecatedLicenseId) l.isDeprecatedLicenseId = true;
}

for (const license of osi) {
  const spdxId = license.identifiers.find(id => id.scheme === 'SPDX');
  if (!spdxId) {
    console.warn(`Skipping ${license.id} (no SPDX id)`);
    continue;
  }

  const id = spdxId.identifier;
  const l = getLicense(id);

  if (!l.id) {
    console.warn(`No SPDX id for OSI license: ${id}`, l);
  } else if (l.id !== id) {
    console.warn(`SPDX id "${l.id}" != OSI id "${id}"`);
  }

  if (license.keywords) {
    l.keywords = license.keywords;
  }

  if (!l.name) {
    console.warn(`No name for ${id}`, l);
  }
}

await fs.writeFile(
  LICENSE_FILE,
  `${JSON.stringify(Object.fromEntries(licenses.entries()), null, 2)}\n`,
);
